### ISSUE TITLE
add email sending 

### ISSUE THREAD

**Issue by hmbilal** [hmbilal/gommon#2]

**Comment by abhichaloo** [comment]
is it genuine to contribute pls acknowledge

**Comment by hmbilal** [comment]
@abhichaloo thanks for asking.
I think at this point, it is better to not do anything as I am collecting all the common code I have written in many projects.
Since I have started this new repository very recently and will try to add more documentation, guidelines, issues.

**Comment by abhichaloo** [comment]
Sure thanks for the info
